apiVersion: v1
kind: Service
metadata:
  name: nogeut-app-service
spec:
  selector:
    app: nogeut-app  # Deployment와 연결될 label
  ports:
    - protocol: TCP
      port: 80         # 클러스터 내에서 사용되는 포트 (외부에서 접속할 포트)
      targetPort: 3030  # 애플리케이션 컨테이너 내부 포트
  type: LoadBalancer  # 클라우드 환경에서는 LoadBalancer, 클러스터 내에서는 ClusterIP

